# Generated by Django 2.2 on 2019-12-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KSG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_type', models.CharField(choices=[('Круглосуточный', 'Круглосуточный'), ('Дневной', 'Дневной')], max_length=10, verbose_name='Тип стационара')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Наименоваие КСГ')),
                ('kz', models.FloatField(verbose_name='КЗ')),
            ],
            options={
                'verbose_name': 'КСГ',
                'verbose_name_plural': 'КСГ',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Код')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_type', models.CharField(choices=[('Круглосуточный', 'Круглосуточный'), ('Дневной', 'Дневной')], max_length=10, verbose_name='Тип стационара')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('mnn', models.CharField(max_length=200, verbose_name='МНН лекарственных препаратов')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование и описание схемы')),
                ('col', models.CharField(max_length=200, verbose_name='Количество дней в тарифе')),
                ('sign', models.CharField(max_length=50, verbose_name='Признак не ЖНВЛП')),
                ('comments', models.TextField(verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Схема лекарственной терапии',
                'verbose_name_plural': 'Схемы лекарственной терапии',
            },
        ),
        migrations.CreateModel(
            name='MKB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='Код')),
                ('diagnosis', models.CharField(max_length=50, verbose_name='Диагноз')),
                ('ksg', models.ManyToManyField(to='med.KSG')),
            ],
            options={
                'verbose_name': 'МКБ 10',
                'verbose_name_plural': 'МКБ 10',
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='ksg',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.Profile', verbose_name='Профиль'),
        ),
    ]
