# Generated by Django 2.2 on 2019-12-26 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='ksg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.KSG', verbose_name='КСГ'),
        ),
    ]
