# Generated by Django 2.2 on 2019-12-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_auto_20191227_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksg',
            name='st_type',
            field=models.CharField(choices=[('Круглосуточный', 'Круглосуточный'), ('Дневной', 'Дневной')], max_length=20, verbose_name='Тип стационара'),
        ),
    ]
