# Generated by Django 2.2 on 2019-12-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Населенный пункт')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Муниципальное образование')),
            ],
            options={
                'verbose_name': 'Муниципальное образование',
                'verbose_name_plural': 'Муниципальные образования',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('birhtdate', models.DateField(verbose_name='Дата рождения')),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Locality', verbose_name='Место жительства')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.AddField(
            model_name='locality',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Municipality', verbose_name='Муниципальное образование'),
        ),
    ]
