# Generated by Django 2.2 on 2019-12-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MKB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='Муниципальное образование')),
                ('diagnosis', models.CharField(max_length=50, verbose_name='Муниципальное образование')),
            ],
            options={
                'verbose_name': 'Код МКБ',
                'verbose_name_plural': 'Код МКБ',
            },
        ),
    ]
