# Generated by Django 2.2 on 2019-12-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191226_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ksg',
            options={'verbose_name': 'КСГ', 'verbose_name_plural': 'КСГ'},
        ),
        migrations.AlterModelOptions(
            name='mkb',
            options={'verbose_name': 'МКБ 10', 'verbose_name_plural': 'МКБ 10'},
        ),
    ]
