# Generated by Django 2.2 on 2019-12-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191226_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='comments',
            field=models.TextField(verbose_name='Примечание'),
        ),
    ]
