# Generated by Django 2.2 on 2019-12-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191226_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Тип стационара')),
                ('name', models.CharField(max_length=50, verbose_name='Тип стационара')),
            ],
            options={
                'verbose_name': 'Схема лекарственной терапии',
                'verbose_name_plural': 'Схемы лекарственной терапии',
            },
        ),
    ]
