# Generated by Django 2.2 on 2019-12-26 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RemoveField(
            model_name='ksg',
            name='profile_code',
        ),
        migrations.RemoveField(
            model_name='ksg',
            name='profile_name',
        ),
        migrations.AddField(
            model_name='ksg',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.IntegerField(verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
    ]
