# Generated by Django 2.2 on 2019-12-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191226_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Locality', verbose_name='Место жительства'),
        ),
        migrations.DeleteModel(
            name='Locality',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
    ]
