# Generated by Django 2.2 on 2019-12-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191226_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ksg',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='mkb',
            name='ksg',
        ),
        migrations.DeleteModel(
            name='Scheme',
        ),
        migrations.DeleteModel(
            name='KSG',
        ),
        migrations.DeleteModel(
            name='MKB',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
