# Generated by Django 2.2 on 2019-12-27 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_auto_20191227_1651'),
        ('main', '0010_auto_20191226_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(verbose_name='Дата поступления')),
                ('date_out', models.DateField(blank=True, null=True, verbose_name='Дата выписки')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.Department', verbose_name='Отделение')),
                ('mkb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.MKB', verbose_name='Диагноз (МКБ 10)')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.Result', verbose_name='Исход заболевания')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.Scheme', verbose_name='Лекарственные препараты')),
            ],
            options={
                'verbose_name': 'Лечение',
                'verbose_name_plural': 'Лечение',
            },
        ),
    ]
