# Generated by Django 2.2 on 2019-12-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Treatment'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.Result', verbose_name='Исход заболевания'),
        ),
    ]
