# Generated by Django 2.2 on 2019-12-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191227_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='st_type',
            field=models.CharField(choices=[('Круглосуточный', 'Круглосуточный'), ('Дневной', 'Дневной')], default='Дневной', max_length=10, verbose_name='Тип стационара'),
            preserve_default=False,
        ),
    ]
