# Generated by Django 2.2 on 2019-12-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20191227_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='mkb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.MKB', verbose_name='Диагноз (МКБ 10)'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='med.Scheme', verbose_name='Лекарственные препараты'),
        ),
    ]
