# Generated by Django 2.2 on 2019-12-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20191227_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='birhtdate',
            new_name='birthdate',
        ),
    ]
